language: python
sudo: false
services: cassandra

env:
  - CASS_DRIVER_NO_CYTHON=1

python:
  - "2.7"
  - "3.4"

addons:
  apt:
    packages:
    - build-essential
    - python-dev
    - pypy-dev
    - libev4
    - libev-dev

install:
  - pip install tox

script:
  - tox
