language: python
sudo: false
services: cassandra

env:
  - DJANGO_VERSION=1.5 CASS_DRIVER_NO_CYTHON=1
  - DJANGO_VERSION=1.6 CASS_DRIVER_NO_CYTHON=1
  - DJANGO_VERSION=1.7 CASS_DRIVER_NO_CYTHON=1
  - DJANGO_VERSION=1.8 CASS_DRIVER_NO_CYTHON=1
  - DJANGO_VERSION=1.9 CASS_DRIVER_NO_CYTHON=1

python:
  - "2.7"
  - "3.4"

addons:
  apt:
    packages:
    - build-essential
    - python-dev
    - pypy-dev
    - libev4
    - libev-dev

install:
  - "pip install django==${DJANGO_VERSION}"
  - python setup.py install

script:
  - "python setup.py test"
