language: python
sudo: false
services: cassandra

env:
  - DJANGO_VERSION=1.5
  - DJANGO_VERSION=1.6
  - DJANGO_VERSION=1.7
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.9

python:
  - "2.7"
  - "3.3"
  - "3.4"

addons:
  apt:
    packages:
    - build-essential
    - python-dev
    - pypy-dev
    - libev4
    - libev-dev

install:
  - "pip install django==${DJANGO_VERSION}"
  - python setup.py install

script:
  - "python setup.py test"
