dist: xenial
language: python
sudo: required
services:
  - cassandra

env:
  matrix:
    - TOX_ENV=py37-django21
    - TOX_ENV=py37-django22
    - TOX_ENV=py37-django30
    - TOX_ENV=py37-djangomaster
  global:
    - CASS_DRIVER_NO_CYTHON=1
    - CASS_HOST=127.0.0.1

python:
  - "3.7"

addons:
  apt:
    packages:
    - build-essential
    - python-dev
    - pypy-dev
    - libev4
    - libev-dev
    - sqlite3

install:
  - pip install tox

script:
  - tox -e $TOX_ENV
