language: python

env:
  - CASSANDRA_VERSION=20
  - DJANGO_VERSION=1.5
  - DJANGO_VERSION=1.6

python:
  - "2.7"

before_install:
  - sudo echo "deb http://www.apache.org/dist/cassandra/debian ${CASSANDRA_VERSION}x main" | sudo tee -a /etc/apt/sources.list
  - sudo echo "deb-src http://www.apache.org/dist/cassandra/debian ${CASSANDRA_VERSION}x main" | sudo tee -a /etc/apt/sources.list
  - sudo gpg --keyserver pgp.mit.edu --recv-keys F758CE318D77295D
  - sudo gpg --export --armor F758CE318D77295D | sudo apt-key add -
  - sudo gpg --keyserver pgp.mit.edu --recv-keys 2B5C1B00
  - sudo gpg --export --armor 2B5C1B00 | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y cassandra
  - sudo sh -c "echo 'JVM_OPTS=\"\${JVM_OPTS} -Djava.net.preferIPv4Stack=false\"' >> /usr/local/cassandra/conf/cassandra-env.sh"
  - sudo service cassandra start
  - if [ "$C_VERSION" -le "20" ]; then export CASSANDRA_PROTOCOL_VERSION=1; fi

install:
  - pip install django==DJANGO_VERSION
  - python setup.py install

script:
  - "python testproject/runtests.py --no-skip"
