dist: bionic
sudo: false

language: python
python:
  - "3.7"

services:
  - cassandra
before_script:
  - bash travis/setup_cassandra.sh

env:
  matrix:
    - TOX_ENV=py37-django21
    - TOX_ENV=py37-django22
    - TOX_ENV=py37-django30
    - TOX_ENV=py37-djangomaster
  global:
    - CASS_DRIVER_NO_CYTHON=1
    - CASS_HOST=127.0.0.1

addons:
  apt:
    packages:
    - build-essential
    - python-dev
    - pypy-dev
    - libc-ares-dev
    - libev4
    - libev-dev
    - sqlite3

install:
  - pip install tox-travis lz4

script:
  - tox -e $TOX_ENV
