site_name: Django Cassandra DB
site_description: Apache Cassandra Database Wrapper for Django
site_url: https://Ariwonto.github.io/django-cassandra-engine
site_author: Aiwonto Team

copyright: Copyright 2020
theme: material
google_analytics: ['UA-125847964-1', 'auto']

repo_name: GitHub
repo_url: https://github.com/Ariwonto/django-cassandra-engine

# Options
extra:
  version: 0.0.1
  logo: images/logo.png
  author:
    github: Ariwonto
    twitter: Ariwonto

# Extensions
markdown_extensions:
  - codehilite
  - admonition
  - toc:
      permalink: '#'

pages:
- Home: 'index.md'
- Django Cassandra DB:
    - 'Installation': 'guide/installation.md'
    - 'Getting Started': 'guide/getting_started.md'
    - 'Advanced Usage': 'guide/advanced_usage.md'
    - 'Management Commands': 'guide/management_commands.md'
    - 'Sessions': 'guide/sessions.md'
    - 'Writing Tests': 'guide/tests.md'
    - 'Contributing': 'guide/contributing.md'
- FAQ: 'faq.md'
- Changelog: 'changelog.md'
- License: 'license.md'
