site_name: Django Cassandra Engine
site_author: Rafał Furmański
copyright: Copyright 2014-2016, <a href="https://rafal-furmanski.com" title="Rafał Furmański homepage" target="_blank">Rafał Furmański</a>
site_description: Cassandra Database Wrapper for Django
site_url: http://r4fek.github.io/django-cassandra-engine
theme: united
google_analytics: ['UA-38726443-3', 'auto']
repo_url: https://github.com/r4fek/django-cassandra-engine
pages:
- [index.md, Home]
- [faq.md, FAQ]
- [changelog.md, Changelog]
