site_name: Django Cassandra Engine
site_author: Rafał Furmański
site_description: Cassandra Database Wrapper for Django
site_url: http://r4fek.github.io/django-cassandra-engine
theme_dir: flatly_custom
repo_url: https://github.com/r4fek/django-cassandra-engine
pages:
- [index.md, Home]
- [faq.md, FAQ]
- [changelog.md, Changelog]

